# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floto', '0003_album_ignore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='ignore',
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.TextField(blank=True, default=b'{}'),
        ),
    ]
